version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=databases
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - intermetalplus


  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      bash -c "python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              gunicorn core.wsgi:application --bind 0.0.0.0:8008 --timeout 10000 --limit-request-field_size 16384 --workers 2"

    volumes:
      - .:/app
      - static_volume:/app/staticfiles

    expose:
      - 8000
    
    depends_on:
      - db

    networks:
      - intermetalplus

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - web

    networks:
      - intermetalplus

volumes:
  postgres_data:
  static_volume:

networks:
  intermetalplus:
    driver: bridge
  

